# Generated by Django 5.0.14 on 2026-08-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileitem",
            name="is_quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fileitem",
            name="quarantine_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fileitem",
            name="risk_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fileitem",
            name="security_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("manual_review", "Manual Review"),
                    ("blocked", "Blocked"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fileitem",
            name="security_summary",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SentinelScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("manual_review", "Manual Review"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(blank=True, default=dict)),
                ("recommendations", models.TextField(blank=True)),
                ("quarantine_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentinel_scans",
                        to="storage.fileitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
