# Generated by Django 5.0.14 on 2026-08-20 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_fileitem_is_quarantined_fileitem_quarantine_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUrlScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2000)),
                ("final_url", models.URLField(blank=True, max_length=2000)),
                ("http_status", models.PositiveIntegerField(default=0)),
                ("redirect_chain", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("manual_review", "Manual Review"),
                            ("blocked", "Blocked"),
                        ],
                        default="manual_review",
                        max_length=20,
                    ),
                ),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("risk_level", models.CharField(default="low", max_length=20)),
                ("summary", models.TextField(blank=True)),
                ("findings", models.JSONField(blank=True, default=dict)),
                (
                    "quarantined_file",
                    models.FileField(
                        blank=True, null=True, upload_to="quarantine/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
