# Generated by Django 5.2.16 on 2026-08-08 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("public", "Public (Anyone with link)"),
                            ("private", "Private (Specific link)"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit Permission"),
                            ("copy", "Copy Permission"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_downloads", models.IntegerField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="storage.fileitem",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="storage.folder",
                    ),
                ),
            ],
        ),
    ]
